### ISSUE TITLE
r.FormValue does not return parameter when it is called in middleware first

### ISSUE THREAD

**Issue by josephspurrier** [husobee/vestigo#28]
I have a RestHandler that allows me to change the HTTP Method via a form field so I can use PATCH and DELETE for actual PATCH and DELETE operations.

When I try to use the middleware code with your router, the http.Request.FormValue function does not return the correct value anymore.

Here is the code:
* https://play.golang.org/p/HYR-Ws6UBt

Here is the output:

* 2016/07/06 03:08:10 Working ID: 4
* 2016/07/06 03:08:10 NotWorking ID:

**Comment by ernestoalejo** [comment]
Vestigo [adds](https://github.com/husobee/vestigo/blob/master/common.go#L54) the var to the query string and `FormValue` [caches](https://golang.org/src/net/http/request.go?s=30758:30804#L1003) the parsed query string. The cached data (`r.Form`) can actually contain data from the query string and data from the body. To reset the cache so you can read vestigo params again `r.Form` should be nil and also `r.Body` should be seeked to the beginning; which is not possible. The alternative is copying the whole body in memory before calling `FormValue` the first time (that is in your code) to keep the old data like [httputil](https://golang.org/src/net/http/httputil/dump.go?s=5737:5808#L25) does to [dump the request](https://golang.org/src/net/http/httputil/dump.go?s=5737:5808#L62) and then [restore it](https://golang.org/src/net/http/httputil/dump.go?s=5737:5808#L123).

When Go 1.7 arrives vestigo could make a decision to store parameters also in the [request context](https://tip.golang.org/pkg/net/http/#Request.Context). Still that wouldn't solve your problem because you're trying to read using `r.FormValue` directly instead of `vestigo.Param`.

**Comment by josephspurrier** [comment]
Ah, awesome, thanks, r.Form = nil under the r.Method = method works.

**Comment by ernestoalejo** [comment]
`r.Form = nil` and read the body into a `bytes.Buffer` or whatever to `Seek` it to the start:

```go
buf := new(bytes.Buffer)
if n, err := io.Copy(buf, r.Body); err != nil {
...
}
r.Body = buf

r.FormValue(...)
r.FormValue(...)

buf.Seek(0, 0)  // 0 bytes from the start (0) of the file

[call vestigo here]
```

It will consume more memory for each request though.

**Comment by josephspurrier** [comment]
Hmm, I don't like the idea of consuming more memory

In https://github.com/husobee/vestigo/blob/master/common.go#L28, is there a reason why you didn't use return r.URL.Query().Get(name)? The URL should work 100% of the time, correct? It seems like the form won't work 100% of the time and anyone with middleware that touches the form before the request will also have this issue.

**Comment by ernestoalejo** [comment]
Note in your original code you where using `r.FormValue(":id")` instead of `vestigo.Param("id")`; that fix you mention wouldn't apply to it.

In `pat` documentation (the inspiration for that pattern of using query string for parameters, according to the blog) they recommend to use:

```go
category := req.URL.Query().Get(":category")
```

so I suppose you are correct it will probably be better to use the URL directly.

**Comment by josephspurrier** [comment]
I see you keep referencing vestigo.Param(). The function does nothing more than add a colon to the beginning of the string so it should have zero difference between `r.FormValue(":id")` and `vestigo.Param("id")`

```go
// Param - Get a url parameter by name
func Param(r *http.Request, name string) string {
	return r.FormValue(":" + name)
}
```

Would you be opposed to changing your code in Param() to use req.URL.Query().Get(":"+name) to cut down on issues that one would experience from parsing the form?

**Comment by josephspurrier** [comment]
Is there a reason you want to use r.Form to hold the URL parameter as opposed to ONLY r.URL?

**Comment by ernestoalejo** [comment]
I said you were correct. I added that `vestigo.Param` is going to do more than `r.FormValue` with the change; so you need to use it (or `r.URL.Query().Get(":" + name)`) instead of `r.FormValue` in your original example (https://play.golang.org/p/HYR-Ws6UBt). As you say, any code already using `vestigo.Param` or `r.URL` don't need to change. Sorry it was not clear.

**Comment by josephspurrier** [comment]
Ok. Last question. Is there a reason you want to use r.Form to hold the URL parameter as opposed to only r.URL? I guess I'm trying to get to why r.FormValue should hold the URL parameter at all.

**Comment by ernestoalejo** [comment]
`r.FormValue` doesn't store values, Vestigo already stores the params in the URL. It then reads them using `FormValue` which triggers this error when `FormValue` has been called previously. The proposed fix is using `r.URL.Query` to read them instead of `FormValue` (https://github.com/husobee/vestigo/blob/master/common.go#L28) which has nothing to do with the way is stored (https://github.com/husobee/vestigo/blob/master/common.go#L46); and I'm supporting the change.

`FormValue` will always return both URL parameters and body parameters because that's the way the standard lib works in Go 1 (https://golang.org/pkg/net/http/#Request.FormValue). That can't change if it's what you're asking.

**Comment by husobee** [comment]
+1, lets make this change.  Will throw something together today and PR it.

**Comment by husobee** [comment]
@josephspurrier: does https://github.com/husobee/vestigo/pull/35 look okay?

**Comment by josephspurrier** [comment]
Looks great, thanks so much!
